name: task_app_2024
description: "Task app with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_it: ^8.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.9
  hive_generator: ^2.0.1
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
